odin-lang/odin-lang.org

content/docs/overview.md

These are all just suggestions. I can change certain things back if you don't like specific changes.

Fix typos and mistakes in overview.md file

---

content/docs/install.md

List Homebrew installation method in documentation. Formula code: https://github.com/Homebrew/homebrew-core/blob/fb34ef5/Formula/odin.rb

Add Homebrew to install docs

---

content/docs/faq.md

Some typos have been fixed, and some grammar corrected.

Fix typos, check grammar

---

content/docs/_index.md

Fix little typo

---

themes/odin/layouts/index.html
themes/odin/layouts/partials/footer.html

Changes:
- Point footer links
- Actually consistent capitalization

Capitalization (again) and footer links

---

themes/odin/layouts/index.html

Let me know what you think / feel free to merge :)
Pictures for comparison:
Live:
New:

Clearer intro wording + fix Learn More button padding

---

themes/odin/layouts/partials/head.html

Pointed out by @matias-eduardo and fixes #40
The last line in the diff gave me a headache, GitHub removed the trailing newline.

Make favicon show on subpages

---

content/docs/overview.md

Not sure if "automatically infer" is the best way to word it. Can update if there's a simpler way to word it.

Add blurb on fixed array length

---

content/docs/overview.md

Add the #any_int and #by_ptr directives to the overview documentation.

---

content/docs/overview.md

I also removed a typo/redundancy in the phrasing. 
Compare the prior text to this commit to see why.

Clarified ambiguities in `or_return` example code.

---

content/docs/overview.md

chore: fix minor typos in overview docs

---

content/docs/overview.md
content/showcase/embergen.md

Here are the 20 pull requests we talked about today on Discord that I accidentally had waiting on my own branch to be merged instead of on the main.

Here's a bunch of typo corrections and clarifications.

---

content/docs/overview.md

Given that Odin currently doesn't have much documentation, I have created an new section at the very end of the Overview page whose purpose is to cover a variety of the most likely ways that the user can find information about how to use Odin above and beyond what actually exists in the docs currently.
Users may not be aware that these useful subdirectories of Odin's source folder exist, especially if they are relatively new to programming. They also may not actually think to use them to try to solve their problems. By including a new section to account for this, Odin can increase the chances of people being able to successfully use the language and decrease the chances of them leaving. It will also make the relative lack of documentation in Odin less intimidating and inspire people to …

Made new section to help b/c Odin's sparse docs.

---

content/docs/install.md

Add atomic.h dep, llvm14 to linux

Add atomic.h dep, llvm14 to linux

---

content/docs/overview.md

Closes odin-lang/Odin/#2493
@Kiyoshi364 I think i have gotten the items that can be readily fixed. Procedures are being documented with examples in the code-docs. An example may be found here: https://github.com/odin-lang/Odin/blob/master/core/strings/builder.odin#L79
If there is anything i missed that is readily repairable please do let me know.

Closes odin-lang/Odin/#2493

---

content/docs/overview.md
content/news/2022-11.md
themes/odin/assets/scss/custom.scss
themes/odin/static/js/script.js

change styling on tables by default, customize table padding-y

---

content/news/binding-to-c.md

The return type of a function was not consistent

Fix binding-to-c.md

---

content/docs/overview.md

This has tripped me up a couple of times, I understand it as the intent here was to say, this is just too good of an opportunity to pass up.

Fixed confusing wording

---

content/docs/overview.md

Fix for issue  #166

---

content/docs/overview.md

Adds all the +=, -=, &&=, etc. operators to its own section
Closes #165

Add compound binary op and assign operators to Overview

---

content/docs/overview.md

Add short description and example of `#optional_allocator_error` directive.

Update the overview to mention #optional_allocator_error

---

content/docs/overview.md

Contains minor tweaks to the wording, and fixes odin-lang/Odin#3087

Update 'Using a vendor library' section

---

content/docs/overview.md

Correct address operator section

---

content/docs/overview.md

Move Bit Fields section above Procedure section

---

content/docs/overview.md

I admit I cheaped out on the `or_break` documentation, but I believe if someone knows what `or_continue` does and what `break` does, they can reasonably infer how it operates, since it follows right after the `or_continue` explanation.

Document `or_continue` and `or_break`

---

content/docs/testing.md

This should be pretty thorough. It was written with beginners in mind.
The bit about the RNG is contingent on https://github.com/odin-lang/Odin/pull/3767 getting merged, but otherwise everything else is good.

Document the new test runner

---

content/docs/install.md

See https://github.com/odin-lang/Odin/issues/3876.

Add information that addresses the `No llvm-config` error

---

content/docs/overview.md

Fixes `//+` -> `#+`
Also added something about excluding multiple platforms.

Use #+ file tags in overview

---

content/docs/install.md

shouldn't be merged until the next release but wanted to update documentation to reflect the new state of our linux builds

update documentation to reflect updated linux builds

---

content/docs/faq.md

Apologies for the very small and low-effort PR. Apparently finding issues in docs is my superpower :upside_down_face:

Fix grammar in FAQ

---

content/showcase/understanding_the_odin_programming_language.md

The text I put it was copy-pasted from the website and didn't suit showcase category like I wanted it to, so I updated it.

Updated the text for the "Understanding the Odin Programming Language" showcase

---

content/docs/overview.md

Just like already done for slices

Should mention the memory layout of fixed arrays

---

content/docs/overview.md

Added @(rodata), @(load_directory), @(fini) and rephrased introduction a bit.

Added a few missing concepts and made introduction a bit friendlier

---

content/community/discord.md
content/community/forum.md
content/community/irc.md
content/community/reddit.md

Someone on IRC asked if we could add the channel to the community page, and I remembered that the unofficial subreddit was talked about being added at one point here https://github.com/odin-lang/Odin/discussions/3202 so I expanded the page a bit.

Expand the Community page

---

content/docs/overview.md

This addition is based on https://x.com/TheGingerBill/status/1906675813153489356

Update overview.md: mention the formal name of untyped types
