content/docs/overview.md

- Remove old mention of underscore prefixes on names causing them not to be exported. (Which no longer works, and was superceded by `private`.)
- Clarify all decls are exported by default.
- Mention `@(private="file")`
- Mention that `@(private)` is equivalent to `@(private="package")`.

Update the "Exported names" section

---

content/docs/overview.md

Adding missing semicolons to `or_return` section of `overview.md`
Addresses: https://github.com/odin-lang/odin-lang.org/issues/47

Adding missing semicolons to `or_return` section

---

content/docs/install.md

homebrew uses a different installation folder if Apple Sillion based

fix(doc): homebrew llvm install

---

content/docs/overview.md

It can used like this:
It can be used like this:

Sentence was missing a word

---

content/docs/install.md

Hello and thank you for the amazing project! I've been looking into the docs and noticed that the `Getting Started` page had some duplicate information on how to install things.
I basically moved the `General Setup` up and changed its name to `Requirements`, added MacOS to its own header and remove the different instruction regarding adding LLVM to the path on Intel and Apple Silicon (Homebrew works the same on both), and did some little changes to Linux instructions.
I tried not to change much for now, I think that it would be good to have a second opinion on this, maybe the `Requirements` can only have the programs/dependencies names and the actual way to install and use them be inside their respective OS explanation. 
I could add FreeBSD/OpenBSD dependencies too, run some VM's and …

Getting Started page restructure

---

content/docs/overview.md

using ODIN_DEBUG instead of DEBUG to make immediately usable.

when debug example to use ODIN_DEBUG

---

content/docs/overview.md

1. `Maybe` shows up in the overview but isn't shown off on its own, and has been asked about a couple of times in 'beginners'.
2. The varargs syntax only shows up once in context with the `#c_vararg` directive. This adds it to Procedures/Parameters and shows off both receiving and calling procedures with varargs.
3. The "Slices may not be allocated using an allocator" language is a FAQ, and I had `make([]int, len, cap) # wrong!` in my notes from my missing that capacity was only settable for dynamic arrays.

overview: add Maybe, Varargs, and touch up making-slices text

---

content/docs/overview.md

-Changed the swizzle example to differentiate between records and indices more easily.
-Added comment about what  equals operator means when one operand is array and the other an int.

more explicit swizzle explanation

---

content/docs/install.md

Homebrew currently installs LLVM 15 by default, which as mentioned in the [release notes for dev-2022-11](https://github.com/odin-lang/Odin/releases/tag/dev-2022-11) does not work yet.
To my great shame I missed that fact when downloading the macOS binaries and spent about an hour figuring out why `odin run hello.odin -file` was complaining about missing libraries under LLVM 15:
```
dyld[96737]: Library not loaded: /usr/local/opt/z3/lib/libz3.4.11.dylib
Referenced from: <D8407A25-548D-3E6A-8EFD-3D4A8FA38EF6> /usr/local/Cellar/llvm/15.0.5/lib/libLLVM.dylib
Reason: tried: '/usr/local/opt/z3/lib/libz3.4.11.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/z3/lib/libz3.4.11.dylib' (no such file), '/usr/local/opt/z3/lib/libz3.4.11.dylib' (no such file), …
```

Prompt users to install llvm@11 on macOS

---

content/docs/overview.md

"By doing so" made it sound like that the next statement (that it kept the fields in source order) was special, when it actually wasn't.

Reword a statement for clarity (Record Memory Layout)

---

content/news/binding-to-c.md

Fixes the 404 for the 'attributes' link at https://odin-lang.org/news/binding-to-c/#foreign-blocks.

Fix attributes link 404 in “Binding to C” news update

---

content/docs/overview.md

I found two small typos in the description of the shift operator in Odin's overview doc page.
There was a missing "is" for the signed integer shift part and the unsigned integer shift part said "the it" when "it" was likely intended. 
However, "it" is grammatically ambiguous here so I further changed "it" to be "the left operand" also instead, so that the sentence is no longer ambiguous.

Fixed two typos in Odin overview docs.

---

content/docs/overview.md

I'm not sure if this is an English dialect difference (I'm American), but the phrase "so with" didn't sound right here.
Thus, I have suggested changing "so with" to "using" because that seems clearer here.

Fixed potential typo in the dynamic array section.

---

content/docs/overview.md

I found another use of deprecated `..` op and changed it to `..=`.
This is the same kind of error as my most recent pull request.

Fixed another use of deprecated `..` op.

---

content/docs/overview.md

`the address to its operand` should be `the address of its operand`.

Fixed typo in the definition of the `&` operator.

---

content/docs/overview.md

The lack of bold here is inconsistent with the style of other instances of "Note:" in the docs.

Fixed lack of bold on "Note:" in parapoly section.

---

content/docs/overview.md

I scanned through the entire document in `gVim` to search for whether there was anymore missing bold formatting and found just one more.
I think that should be the last.

Scanned for and fixed all missing bold "Note:"s.

---

content/docs/overview.md

I'm still new to Odin, so I'm not 100% sure, but I've tested this behavior and the edited description I've given here seems more accurate and clarifying.
The previous vague mention of "constant" was highly confusing and didn't paint the pull picture clearly enough.

Clarified meaning of "constant" for `$` parameters

---

themes/odin/layouts/partials/footer.html

When looking at the website, I randomly noticed that the copyright year number for Odin for Ginger Bill was still "2016-2022".
Thus, I found this footer HTML file and edited it here.
Is this the correct way to fix that for the site? Should I be fixing it?
In any case, I thought you should know, and so I'm submitting this proposed change.

Updated copyright year range for the Odin site.

---

content/docs/overview.md

- Moved attributes and directives sections out of the idioms section
- Changed attributes and directives into headers vs bold list items
- Added `@(extra_linker_flags=<string>)` attribute
- Added `@(optimization_mode=<string>)` attribute

Attributes and directives section update

---

content/docs/overview.md

Surprisingly, I discovered that the several mechanisms Odin provides for handling conditional compilation aren't mentioned anywhere in overview. Not even the file suffixes!
Given that quite a few people have asked about this before, and that there is basically no mention of it at all, I've gone ahead and made a section about it.
This section fleshes out how `when` statements can be used for this, as well as the file suffixes, `-define`s, and build tags.
It also mentions the otherwise-undocumented build tags using language that makes it clear that users should generally prefer the file suffixes if that covers their use-cases, as the build tags are something of a specialised thing that we don't want being abused.

Add a section on Conditional Compilation

---

content/docs/overview.md

I suggest reviewing changes per-commit.
Used this command to find code blocks without language specified, could be useful to check other files:
```
awk '/^```/ { inside=!inside; if(inside) bad=($0=="```"); else if(bad) print NR": "$0"\n"; } inside && bad { print NR": "$0 }' content/docs/overview.md
```

Improve overview.md code highlighting

---

content/docs/overview.md

I used the tracking allocator example provided in the overview to check that I didn't have any leaks, after patching up my code I noticed that valgrind was still reporting a single un-freed allocation and after much frustration I discovered that it was in the snippet that I yoinked from the docs that was causing it lol.
Command: `valgrind --leak-check=full ./a.out` 
<details>
<summary>Before</summary>
```
==28155== HEAP SUMMARY:
==28155==     in use at exit: 9,607 bytes in 1 blocks
==28155==   total heap usage: 10 allocs, 9 frees, 26,646 bytes allocated
==28155==
==28155== 9,607 bytes in 1 blocks are definitely lost in loss record 1 of 1
==28155==    at 0x4842794: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==28155==    by 0x43D842: os.heap_alloc …
```

Fix memory leak in tracking allocator example

---

content/docs/overview.md

Temp allocator implementation was changed to arena allocator in [dev-2023-03](https://github.com/odin-lang/Odin/releases/tag/dev-2023-03), but overview page still mentioned a ring-buffer. This is now updated to match the current implementation.

update mention of temp_allocator (no longer ring based)

---

content/docs/overview.md

Changes: 
- Fix typo in the "Multi-pointers" section. Mutli-pointers -> Multi-pointers

Fix Typo in overview.md

---

content/docs/overview.md

Code comments used single quotes, double quotes and back-ticks interchangeably to signify an in-line code block. Periods were infrequently used to terminate a comment.
These changes use back-ticks for all in-line code blocks and remove all terminating periods to improve consistency of the commenting style.
In addition, a few phrases were given slight rewrites to increase clarity or remove typos.

More consistent comments in overview.md

---

content/docs/overview.md

I found a small mistake.
The docs gives the interval notation [a,b] and says the upper limit is exclusive. I think it should be [a,b).
BTW grate language.

fix mistake overview.md

---

content/docs/faq.md

Fixed doubled 'the' typo in _What is the difference between free and delete?_:
delete deinitializes the **the** slice, dynamic array, map, and string types.

Fixed typo in faq.md

---

content/docs/overview.md

load_or no longer exists. Instead add the load() or_else explanation.
Closes #164

Remove load_or section

---

content/docs/faq.md
content/docs/overview.md
themes/odin/layouts/partials/odin-examples/context-system.html

There are a few sentences on Odin's site which are worded in a way that assumes all users/programmers are a specific gender, which should be avoided.
The first C.A.R Hoarse quote on the FAQ page also uses similar gendered language. It feels irresponsible to alter/paraphrase it so I've left it unaltered for now, but I still want to bring attention to it to invite more input about how best to handle it.

Remove gendered language

---

content/docs/overview.md

This section of the overview was still using an index to write into an array as if there was no way to do a range based for loop that could mutate the contents

Add section on by-reference range based for loop

---

content/docs/overview.md

PR adds some documentation to the Overview regarding the procedure attribute `@(test)` and the filename suffix `_test`.
I hope my understanding is correct.

Add to Overview about @(test) and _test

---

content/showcase/solar_storm.md

I added the game I'm working on to the Showcase page. Any feedback on the page is very welcome.
Currently it shows the steam demo, but once the full game releases I'll update the page.

Add Solar Storm to Showcase page

---

content/docs/overview.md

As far as I can tell, gb has deprecated this:
https://github.com/odin-lang/Odin/commit/59575d9b22c09133438e44deaf4e39f8bd9ab459

Remove outdated bitset info

---

content/docs/overview.md

I figured it helped to make this explicit. Even though the explanation says "labeled construct," it might not be as clear that you can do this with a plain block.

Document labeled block `break`

---

content/community/how-you-can-help.md

"Source code" was written twice and there was a typo for "financial support" title, so I corrected that.

Fixed typos on the help page

---

content/docs/overview.md

It now reads `was not nil or was false` to clarify it is different between `nil`-able types and `bool`
Also add an example with ok semantics to demonstrate

Clarify or_return semantics

---

content/docs/faq.md

A similar change to https://github.com/odin-lang/odin-lang.org/pull/206; this will be my final communication about this topic.
In my understanding, this paragraph is attempting to complain about implicit numeric type conversion in C. However, it currently implies it was a good thing in C, because of what it says outweighs what. This change flips the order.
This pr also makes two other slight corrections to enhance readability.

Update faq.md - flip "confusion" and "convenience" in "is outweighed by" clause.

---

themes/odin/static/css/style.css

fixes #195
from https://odin-lang.org/docs/overview:
<br/><br/>
from https://odin-lang.org/news/newsletter-2024-06:
<br/><br/>
The weird solution with `td {width: 1%;}` is required for the table to keep taking the whole space on decktop.
Other solution would be to use media queries to only apply `table {display: block; overflow-x: auto;}` on mobile

Fix document width overflows caused by long links and tables

---

content/docs/overview.md

Two octal digits are 6 bits wide. One octal digit (0-7) are 3 bit wide.

Two octal digits are 6 bits wide.

---

content/docs/install.md

Based on the code found in `build_odin.sh`, it appears that LLVM 18 is supported:
```sh
if [ -z "$LLVM_CONFIG" ]; then
if   [ -n "$(command -v llvm-config-18)" ]; then LLVM_CONFIG="llvm-config-18"
elif [ -n "$(command -v llvm-config-17)" ]; then LLVM_CONFIG="llvm-config-17"
elif [ -n "$(command -v llvm-config-14)" ]; then LLVM_CONFIG="llvm-config-14"
elif [ -n "$(command -v llvm-config-13)" ]; then LLVM_CONFIG="llvm-config-13"
elif [ -n "$(command -v llvm-config-12)" ]; then LLVM_CONFIG="llvm-config-12"
elif [ -n "$(command -v llvm-config-11)" ]; then LLVM_CONFIG="llvm-config-11"
elif [ -n "$(command -v llvm-config18)" ]; then  LLVM_CONFIG="llvm-config18"
elif [ -n "$(command -v llvm-config17)" ]; then  LLVM_CONFIG="llvm-config17"
elif [ -n "$(command -v llvm-config14)" ]; then …
```

Update install instructions to include LLVM 18 as an acceptable version

---

content/docs/overview.md

Just a few objective typos I noticed whilst reading the overview!

Fix typos in overview

---

content/docs/faq.md

I corrected typos (including formatting) that I found while reading the faq page.

Correct some typos in faq

---

content/docs/install.md

Made 'getting started' page clearer:
- Less stuff is repeated and text is more to-the-point
- It is clearer what to do when using a binary release.
- It is clear that you should prefer release builds unless you want to troubleshoot compiler
- There are upgrade instructions for binary releases

"Getting started" clarifications

---

content/docs/overview.md

Surely this will ensure no one will ever be as confused with 'link_prefix' as I was with 'link_name'.

Changed the 'link_prefix' section to be in line with the 'link_name' section

---

themes/odin/static/js/script.js

Fixes this kind of issue: https://discord.com/channels/568138951836172421/884757242220515350/1270450230537486347
The issue is within the code that automatically scrolls the table of contents. But for some reason that scrolling sometimes affects the main view, making the main view get stuck and jitter. It seems to happen when a giant section such as 'Advanced types' comes into view. That section is bigger than the vertical height of the table of contents scrollable view. I assume it then somehow tries to scroll the outer view to try to fix it.
Setting `behavior: smooth` on the `scrollIntoView` call fixes it (and also makes the automatic scrolling of the table of contents behave in a smooth cute way). Not 100% sure why it fixes it, but I assume the previous issues where some kind of …

Fix for overview jitter when scrolling around

---

themes/odin/static/js/script.js

Second fix for table-of-contents scroll jitter. Previous fix (https://github.com/odin-lang/odin-lang.org/pull/234) introduced another issue where the scroll suddenly stopped when scrolling downwards. However, I realized I can just scroll the anchor into view instead of the whole list element. The anchor is always just one row high while list element is arbitrarily big. So just scrolling to anchor stops `scrollIntoView` from getting confused. This makes the original problem go away. Removed the smooth scrolling since it caused issues.

Better fix for overview jitter bug

---

content/docs/overview.md

Found this neat trick on discord but it isn't in the docs, thought it might be useful - feel free to close otherwise
> Yep.
> [?]int{0..<16 = 123}
> But note that if you want a slice, you'll probably need to do an explicit copy, or slice.fill
https://discord.com/channels/568138951836172421/568871298428698645/1269783875459088436

document range operation for array initialization

---

themes/odin/layouts/index.html

Thank you to everyone who Odin
->
Thank you to everyone who sponsor Odin

Missing word 'sponsor' on bottom of front page.

---

content/docs/overview.md

Simple fix. The link is currently broken.
This link may help to check it:
https://odin-lang.org/docs/overview/#enumerated-array

overview.md: fixing typo of link to enumarated-array section

---

content/docs/overview.md

The Overview page's first [`switch`](https://odin-lang.org/docs/overview/#switch-statement) example doesn't compile for me:
```odin
// Error: `Unhandled switch case: riscv64
//        Suggestion: Was '#partial switch' wanted?`.
switch arch := ODIN_ARCH; arch {
case .i386, .wasm32, .arm32:
fmt.println("32-bit")
case .amd64, .wasm64p32, .arm64:
fmt.println("64-bit")
case .Unknown:
fmt.println("Unknown architecture")
}
```
I think this error might have been introduced via https://github.com/odin-lang/Odin/commit/ca6ef95b038f3eb443971240de73924a721485cc#diff-af3b32e62b98194a113e63df5270f8c2aa32a0ef7a003def33bf33c27d9eb335.
This PR just rolls the new `.riscv64` case into the "64 bit" group.
I'm compiling on `dev-2024-09`, on macOS.
~
```bash
$ odin version
odin version dev-2024-09:16c5c69a4 …
```

Checks all cases;

---

themes/odin/assets/scss/custom.scss

So links to things like keywords, packages, etc are more apparent. Only applies to the article, sidenav is still the same.
Example:

Add underline to inline code links

---

content/docs/overview.md

Before this the tracking allocator example was waaaay down below a long list of constants in a section on the `when` statement. It was hard to link to.
Now it has its own subsection under allocators and there are some new links to find your way around.

Move tracking allocator example to a subsection of allocators

---

content/docs/overview.md

Added directory directive to Overview.

---

themes/odin/static/js/script.js

This pull request aims to fix https://github.com/odin-lang/odin-lang.org/issues/256
Instead of changing the active section every time a new header scrolls into view the active section is only changed when the current section header scrolls out of view and a next section header is visible. 
See the attached video for comparison of the new (left) and old (right) behaviour.
[Screencast_20241111_135747.webm](https://github.com/user-attachments/assets/a4b0da94-1141-4ba4-b2ee-2699064afc85)

improve the behaviour of section higlighting in table of contents

---

content/docs/overview.md

Fix docs for octal escape char

---

content/docs/overview.md

It doesn't do anything anymore, nothing is ever added to `track.bad_free_array` unless `track.bad_free_callback` is set to `mem.tracking_allocator_bad_free_callback_add_to_array`

Remove the bad free array checking from the tracking allocator setup example

---

themes/odin/layouts/partials/head.html
themes/odin/theme.toml

Fixes
```
ERROR deprecated: resources.ToCSS was deprecated in Hugo v0.128.0 and will be removed in Hugo 0.143.0. Use css.Sass instead.
```
by switching from `resources.ToCSS` to `css.Sass` and requiring minimum of Hugo v0.128 installed.

fix: update hugo `min_version` and switch to `css.Sass`

---

content/docs/overview.md

Came across this typo while reading the Overview. Small fix from `progarm` to `program`.

Typo fix in overview.md

---

content/docs/overview.md

This is in response to odin-lang/Odin#5207

Document interaction between `---` and struct padding

---

content/docs/overview.md

Got a compiler error attempting to use a label with a conditional. Clarified the example to demonstrate that it does work and you need to specify the label when doing this.

Clarify break statement when used with a conditional
